### PR TITLE
Update plugin.js

### PR DESCRIPTION
**Pull request by blakstrox**
Changed alert path to match with the latest KeeWeb Version

### CODE REVIEW

**Comment by blakstrox** [comment]
Please resign the plugin with this change

**Comment by vavrecan** [comment]
thank you

**Comment by blakstrox** [comment]
Hi Marek,

Thank you. However, it seems that the plugin needs to be resigned to work
it. Can you please help to update that also?. Thank you so much for your
time in developing this plugin. This plugin makes a lot of sense to me.

Please see the attached screenshot for your reference.

Regards,
Vishnu

**Comment by vpcvishnu** [comment]
js-sign-issue

**Comment by blakstrox** [comment]
js-sign-issue

**Comment by blakstrox** [comment]
@vavrecan Please help to resign it

**Pull request merged**
